//
//  RestByMood+Restaurants.swift
//  Vibefy
//
//  Created by Guilherme Souza on 15/09/22.
//

// MARK: - RestByMood + Restaurants

import Foundation
import UIKit

class RestByMoodFunc {
    
    func restaurants() -> [Mood] {
        
        return [
            
            // MARK: - mood: INTROSPECTIVO
            
            Mood(mood: "introspectiva", suggestions: [RestByMood (name: "Café 81",
                                                                  type: "Coffee Shop",
                                                                  price: "$$",
                                                                  rating: "4,7",
                                                                  address: "R. das Creoulas, 55A",
                                                                  bairro: "Graças",
                                                                  maskImage: UIImage(named: "81cafe-mask"),
                                                                  backImage: UIImage(named: "81cafe-back"),
                                                                  filters: [
                                                                    "Vegano",
                                                                    "Vegetariano"
                                                                  ],
                                                                  drinks: false),
                                                      
                                                      RestByMood(name: "Versado",
                                                                 type: "Coffee Shop",
                                                                 price: "$$",
                                                                 rating: "4,9",
                                                                 address: "R. do Cupim, 259 - Graças",
                                                                 bairro: "Graças",
                                                                 maskImage: UIImage(named: "versado-mask"),
                                                                 backImage: UIImage(named: "versado-back"),
                                                                 filters: [
                                                                    
                                                                 ],
                                                                 drinks: false),
                                                      RestByMood(name: "Lala Café & Cozinha Afetiva",
                                                                 type: "Coffee Shop",
                                                                 price: "$$-$$$",
                                                                 rating: "4,4",
                                                                 address: "R. Amélia, 470 - Graças",
                                                                 bairro: "Graças",
                                                                 maskImage: UIImage(named: "lala-mask"),
                                                                 backImage: UIImage(named: "lala-back"),
                                                                 filters: [
                                                                    "Vegano",
                                                                    "Vegetariano"
                                                                 ],
                                                                 drinks: false),
                                                      RestByMood(name: "Borsoi",
                                                                 type: "Coffee Shop",
                                                                 price: "$$",
                                                                 rating: "4,6",
                                                                 address: "Rua Artur Muniz 82, Boa Viagem",
                                                                 bairro: "Graças",
                                                                 maskImage: UIImage(named: "borsoi-mask"),
                                                                 backImage: UIImage(named: "borsoi-back"),
                                                                 filters: [
                                                                    "Vegano",
                                                                    "Vegetariano"
                                                                 ],
                                                                 drinks: false),
                                                      RestByMood(name: "Galo Padeiro",
                                                                 type: "Coffee Shop, Diner",
                                                                 price: "$$-$$$",
                                                                 rating: "4,6",
                                                                 address: "R. Cap. Lima, 82 - Santo Amaro",
                                                                 bairro: "Graças",
                                                                 maskImage: UIImage(named: "galopadeiro-mask"),
                                                                 backImage: UIImage(named: "galopadeiro-back"),
                                                                 filters: [
                                                                    "Vegano",
                                                                    "Vegetariano"
                                                                 ],
                                                                 drinks: false),
                                                      RestByMood(name: "Café mais prosa",
                                                                 type: "Coffee Shop",
                                                                 price: "$",
                                                                 rating: "4,6",
                                                                 address: "Rua Barão de Itamaracá 284, Loja 4",
                                                                 bairro: "Graças",
                                                                 maskImage: UIImage(named: "cafemaisprosa-mask"),
                                                                 backImage: UIImage(named: "cafemaisprosa-back"),
                                                                 filters: [
                                                                    
                                                                 ],
                                                                 drinks: false)]
                ),
            
            // MARK: - mood: VIBRANTE
            
            Mood(mood: "vibrante", suggestions: [RestByMood(name: "Porpino’s Burger",
                                                            type: "Hamburgueria",
                                                            price: "$$",
                                                            rating: "4,8",
                                                            address: "Av. Conselheiro Aguiar, 1275 - Boa Viagem",
                                                            bairro: "Graças",
                                                            maskImage: UIImage(named: "porpino-mask"),
                                                            backImage: UIImage(named: "porpino-back"),
                                                            filters: [
                                                                "Vegano",
                                                                "Vegetariano"
                                                            ],
                                                            drinks: true),
                                                 RestByMood(name: "Terraço Carvalheira",
                                                            type: "Brasileira, Bar, Churrasco",
                                                            price: "$$-$$$$",
                                                            rating: "4,4",
                                                            address: "R. Padre Carapuceiro, 777 - Edifício Garagem (Cobertura B4 - Boa Viagem)",
                                                            bairro: "Graças",
                                                            maskImage: UIImage(named: "terraco-mask"),
                                                            backImage: UIImage(named: "terraco-back"),
                                                            filters: [
                                                                
                                                            ],
                                                            drinks: true)]
                ),
            
            // MARK: - mood: TRANQUILO
            
            Mood(mood: "tranquila", suggestions: [RestByMood(name: "Borsoi",
                                                             type: "Coffee Shop",
                                                             price: "$$",
                                                             rating: "4,6",
                                                             address: "Rua Artur Muniz 82, Boa Viagem",
                                                             bairro: "Graças",
                                                             maskImage: UIImage(named: "borsoi-mask"),
                                                             backImage: UIImage(named: "borsoi-back"),
                                                             filters: [
                                                                "Vegano",
                                                                "Vegetariano"
                                                             ],
                                                             drinks: false),
                                                  RestByMood(name: "Tokyo's Cafe",
                                                             type: "Coffee Shop",
                                                             price: "$$-$$$",
                                                             rating: "4,6",
                                                             address: "Av. Dr. Malaquias, 79 - Graças",
                                                             bairro: "Graças",
                                                             maskImage: UIImage(named: "tokyos-mask"),
                                                             backImage: UIImage(named: "tokyos-back"),
                                                             filters: [
                                                                "Vegano",
                                                                "Vegetariano"
                                                             ],
                                                             drinks: false),
                                                  RestByMood(name: "Amanita",
                                                             type: "Hamburgueria Vegana",
                                                             price: "$$$",
                                                             rating: "4,6",
                                                             address: "R. Guimarães Peixoto, 37 - Casa Amarela",
                                                             bairro: "Graças",
                                                             maskImage: UIImage(named: "amanita-mask"),
                                                             backImage: UIImage(named: "amanita-back"),
                                                             filters: [
                                                                "Vegano",
                                                                "Vegetariano"
                                                             ],
                                                             drinks: true),
                                                  RestByMood(name: "Melhor Cantinho da Cidade",
                                                             type: "Coffee Shop",
                                                             price: "$",
                                                             rating: "4,6",
                                                             address: "R. Azeredo Coutinho, 10 - Várzea",
                                                             bairro: "Graças",
                                                             maskImage: UIImage(named: "melhorcantinho-mask"),
                                                             backImage: UIImage(named: "melhorcantinho-back"),
                                                             filters: [
                                                                "Vegano",
                                                                "Vegetariano"
                                                             ],
                                                             drinks: false),
                                                  RestByMood(name: "A Vida é Bela",
                                                             type: "Coffee Shop",
                                                             price: "$$",
                                                             rating: "4,6",
                                                             address: "R. Francisco Lacerda, 394 - Várzea",
                                                             bairro: "Graças",
                                                             maskImage: UIImage(named: "avidaebela-mask"),
                                                             backImage: UIImage(named: "avidaebela-back"),
                                                             filters: [
                                                                "Vegano",
                                                                "Vegetariano"
                                                             ],
                                                             drinks: false),
                                                  RestByMood(name: "Manu Tenório Culinária Saudável",
                                                             type: "Brasileira, Café, Saudável",
                                                             price: "$$-$$$",
                                                             rating: "5,0",
                                                             address: "Avenida Rui Barbosa 1503",
                                                             bairro: "Graças",
                                                             maskImage: UIImage(named: "manutenorio-mask"),
                                                             backImage: UIImage(named: "manutenorio-back"),
                                                             filters: [
                                                                "Vegano",
                                                                "Vegetariano"
                                                             ],
                                                             drinks: false),
                                                  RestByMood(name: "Vila Amizade Padaria Artesanal",
                                                             type: "Padaria",
                                                             price: "$$$",
                                                             rating: "4,6",
                                                             address: "Rua Da Amizade, 54, Graças",
                                                             bairro: "Graças",
                                                             maskImage: UIImage(named: "vilaamizade-mask"),
                                                             backImage: UIImage(named: "vilaamizade-back"),
                                                             filters: [
                                                                "Vegetariano"
                                                             ],
                                                             drinks: false),
                                                  RestByMood(name: "O Pátio",
                                                             type: "Coffee Shop",
                                                             price: "$$",
                                                             rating: "4,5",
                                                             address: "Av. Rui Barbosa, 141 - Graças",
                                                             bairro: "Graças",
                                                             maskImage: UIImage(named: "opatio-mask"),
                                                             backImage: UIImage(named: "opatio-back"),
                                                             filters: [
                                                                
                                                             ],
                                                             drinks: false),
                                                  RestByMood(name: "Café com Dengo",
                                                             type: "Coffee Shop",
                                                             price: "$$-$$$",
                                                             rating: "4,5",
                                                             address: "R. Desembargador Martins Pereira, 45, Rosarinho",
                                                             bairro: "Graças",
                                                             maskImage: UIImage(named: "cafecomdengo-mask"),
                                                             backImage: UIImage(named: "cafecomdengo-back"),
                                                             filters: [
                                                                "Vegano",
                                                                "Vegetariano"
                                                             ],
                                                             drinks: false)]
                ),
            // MARK: - mood: ROMÂNTICO
            
            Mood(mood: "romantica", suggestions: [RestByMood(name: "Tokyo's Cafe",
                                                             type: "Coffee Shop",
                                                             price: "$$-$$$",
                                                             rating: "4,6",
                                                             address: "Av. Dr. Malaquias, 79 - Graças",
                                                             bairro: "Graças",
                                                             maskImage: UIImage(named: "tokyos-mask"),
                                                             backImage: UIImage(named: "tokyos-back"),
                                                             filters: [
                                                                "Vegano",
                                                                "Vegetariano"
                                                             ],
                                                             drinks: false),
                                                  RestByMood(name: "La Pecora Nera",
                                                             type: "Italiana",
                                                             price: "$$$$",
                                                             rating: "4,5",
                                                             address: "Praça de Casa Forte, 505 - Casa Forte",
                                                             bairro: "Graças",
                                                             maskImage: UIImage(named: "pecoranera-mask"),
                                                             backImage: UIImage(named: "pecoranera-back"),
                                                             filters: [
                                                                "Vegano",
                                                                "Vegetariano"
                                                             ],
                                                             drinks: true),
                                                  RestByMood(name: "La Tratoria",
                                                             type: "Italiana, Massas",
                                                             price: "$$-$$$",
                                                             rating: "4,5",
                                                             address: "Rua Carlos Pereira Falcão 334 - Boa Viagem",
                                                             bairro: "Graças",
                                                             maskImage: UIImage(named: "latratoria-mask"),
                                                             backImage: UIImage(named: "latratoria-back"),
                                                             filters: [
                                                                "Vegano",
                                                                "Vegetariano",
                                                                "Saudável"
                                                             ],
                                                             drinks: true),
                                                  RestByMood(name: "Lupi Pizzeria",
                                                             type: "Italiana, Pizza",
                                                             price: "$$-$$$",
                                                             rating: "5,0",
                                                             address: "R. José Domingues da Silva, 238 - Boa Viagem",
                                                             bairro: "Graças",
                                                             maskImage: UIImage(named: "lupi-mask"),
                                                             backImage: UIImage(named: "lupi-back"),
                                                             filters: [
                                                                "Vegano",
                                                                "Vegetariano"
                                                             ],
                                                             drinks: true),
                                                  RestByMood(name: "Chiwake",
                                                             type: "Peruana, Latina, Frutos do Mar",
                                                             price: "$$$$",
                                                             rating: "4,5",
                                                             address: "R. da Hora, 820 - Espinheiro",
                                                             bairro: "Graças",
                                                             maskImage: UIImage(named: "chiwake-mask"),
                                                             backImage: UIImage(named: "chiwake-back"),
                                                             filters: [
                                                                "Vegano",
                                                                "Vegetariano"
                                                             ],
                                                             drinks: true),
                                                  RestByMood(name: "Jojoo Creative Sushi",
                                                             type: "Japonesa, Frutos do Mar, Sushi",
                                                             price: "$$$$",
                                                             rating: "4,5",
                                                             address: "Av. Conselheiro Aguiar, 802 - Boa Viagem",
                                                             bairro: "Graças",
                                                             maskImage: UIImage(named: "jojoo-mask"),
                                                             backImage: UIImage(named: "jojoo-back"),
                                                             filters: [
                                                                "Vegano",
                                                                "Vegetariano"
                                                             ],
                                                             drinks: true),
                                                  RestByMood(name: "Anjo Solto",
                                                             type: "Francesa, Brasileira, Contemporânea",
                                                             price: "$$-$$$",
                                                             rating: "4,5",
                                                             address: "R. Herculano Bandeira, 513 - Pina",
                                                             bairro: "Graças",
                                                             maskImage: UIImage(named: "anjosolto-mask"),
                                                             backImage: UIImage(named: "anjosolto-back"),
                                                             filters: [
                                                                "Vegano",
                                                                "Vegetariano",
                                                                "Saudável"
                                                             ],
                                                             drinks: true),
                                                  RestByMood(name: "Le Chef Bistro",
                                                             type: "Francesa",
                                                             price: "$$$$",
                                                             rating: "4,5",
                                                             address: "Av. Eng. Domingos Ferreira, 1097 - Boa Viagem",
                                                             bairro: "Graças",
                                                             maskImage: UIImage(named: "lechef-mask"),
                                                             backImage: UIImage(named: "lechef-back"),
                                                             filters: [
                                                                "Vegano",
                                                                "Vegetariano",
                                                                "Saudável",
                                                                "Opções sem Gluten"
                                                             ],
                                                             drinks: true)]
                ),
            
            // MARK: - mood: INTENSO
            
            Mood(mood: "intensa", suggestions: [RestByMood(name: "Rock & Ribs",
                                                           type: "Americana, Churrascaria",
                                                           price: "$$-$$$",
                                                           rating: "4,5",
                                                           address: "Av. Alfredo Lisboa, S/N - Marco Zero",
                                                           bairro: "Graças",
                                                           maskImage: UIImage(named: "rocknribs-mask"),
                                                           backImage: UIImage(named: "rocknribs-back"),
                                                           filters: [
                                                            "Vegano",
                                                            "Vegetariano"
                                                           ],
                                                           drinks: true),
                                                RestByMood(name: "Outback Steakhouse",
                                                           type: "Australiana, Churrascaria",
                                                           price: "$$-$$$",
                                                           rating: "4,6",
                                                           address: "R. Padre Carapuceiro, 777 - Boa Viagem",
                                                           bairro: "Graças",
                                                           maskImage: UIImage(named: "outback-mask"),
                                                           backImage: UIImage(named: "outback-back"),
                                                           filters: [
                                                            "Vegano",
                                                            "Vegetariano"
                                                           ],
                                                           drinks: true),
                                                RestByMood(name: "Carranca Bar",
                                                           type: "Argentina, Bar",
                                                           price: "$$",
                                                           rating: "4,5",
                                                           address: "Av. 17 de agosto - 1778",
                                                           bairro: "Graças",
                                                           maskImage: UIImage(named: "carranca-mask"),
                                                           backImage: UIImage(named: "carranca-back"),
                                                           filters: [
                                                            
                                                           ],
                                                           drinks: true),
                                                RestByMood(name: "Babylon Station",
                                                           type: "Petiscos, Bar",
                                                           price: "$$-$$$",
                                                           rating: "4,5",
                                                           address: "Rua Nestor Silva 162 - Santana",
                                                           bairro: "Graças",
                                                           maskImage: UIImage(named: "babylon-mask"),
                                                           backImage: UIImage(named: "babylon-back"),
                                                           filters: [
                                                            "Vegano",
                                                            "Vegetariano"
                                                           ],
                                                           drinks: true),
                                                RestByMood(name: "Vaporetto",
                                                           type: "Bar",
                                                           price: "$$-$$$",
                                                           rating: "4,3",
                                                           address: "R. Leopoldino Silva, 100 - Santana",
                                                           bairro: "Graças",
                                                           maskImage: UIImage(named: "vaporetto-mask"),
                                                           backImage: UIImage(named: "vaporetto-back"),
                                                           filters: [
                                                            
                                                           ],
                                                           drinks: true),
                                                RestByMood(name: "Barchef Boteco",
                                                           type: "Bar",
                                                           price: "$$-$$$",
                                                           rating: "4,5",
                                                           address: "Av. Conselheiro Aguiar, 2814 - Boa-Viagem",
                                                           bairro: "Graças",
                                                           maskImage: UIImage(named: "barchef-mask"),
                                                           backImage: UIImage(named: "barchef-back"),
                                                           filters: [
                                                            
                                                           ],
                                                           drinks: true),
                                                RestByMood(name: "Liamba",
                                                           type: "Petiscos, Bar",
                                                           price: "$$",
                                                           rating: "4,5",
                                                           address: "R. Fernando Lopes, 78 - Graças",
                                                           bairro: "Graças",
                                                           maskImage: UIImage(named: "liamba-mask"),
                                                           backImage: UIImage(named: "liamba-back"),
                                                           filters: [
                                                            
                                                           ],
                                                           drinks: true)]
                ),
            // MARK: - mood: PRAIEIRO
            Mood(mood: "praieira", suggestions: [RestByMood(name: "Entre Amigos Praia",
                                                            type: "Brasileira, Frutos do Mar",
                                                            price: "$$$",
                                                            rating: "4,6",
                                                            address: "Av. Boa Viagem, 760 - Boa-Viagem",
                                                            bairro: "Graças",
                                                            maskImage: UIImage(named: "entreamigos-mask"),
                                                            backImage: UIImage(named: "entreamigos-back"),
                                                            filters: [
                                                                "Vegano",
                                                                "Vegetariano"
                                                            ],
                                                            drinks: true),
                                                 RestByMood(name: "Barraca da Edite",
                                                            type: "Petiscos, Drinks",
                                                            price: "$$",
                                                            rating: "5",
                                                            address: "Av. Boa Viagem, 760 - Boa-Viagem",
                                                            bairro: "Graças",
                                                            maskImage: UIImage(named: "barracadaedite-mask"),
                                                            backImage: UIImage(named: "barracadaedite-back"),
                                                            filters: [
                                                                "Vegano",
                                                                "Vegetariano"
                                                            ],
                                                            drinks: true),
                                                 RestByMood(name: "Rota do Mar",
                                                            type: "Frutos do Mar",
                                                            price: "$$-$$$",
                                                            rating: "4,6",
                                                            address: "R. José de Souza Marmelo, 112, Barra-de-Jangada",
                                                            bairro: "Graças",
                                                            maskImage: UIImage(named: "rotadomar-mask"),
                                                            backImage: UIImage(named: "rotadomar-back"),
                                                            filters: [
                                                                
                                                            ],
                                                            drinks: true),
                                                 RestByMood(name: "Bar do Cabo",
                                                            type: "Frutos do Mar",
                                                            price: "$$",
                                                            rating: "4,7",
                                                            address: "R. Nanuque, 37 - Brasília Teimosa",
                                                            bairro: "Graças",
                                                            maskImage: UIImage(named: "bardocabo-mask"),
                                                            backImage: UIImage(named: "bardocabo-back"),
                                                            filters: [
                                                                
                                                            ],
                                                            drinks: false),
                                                 RestByMood(name: "Seu Tito Praia",
                                                            type: "Brasileira",
                                                            price: "$$",
                                                            rating: "4,5",
                                                            address: "R. Artur Muniz, 82 - Boa Viagem",
                                                            bairro: "Graças",
                                                            maskImage: UIImage(named: "seutitopraia-mask"),
                                                            backImage: UIImage(named: "seutitopraia-back"),
                                                            filters: [
                                                                
                                                            ],
                                                            drinks: true)]
                ),
            // MARK: - mood: ALEGRE
            Mood(mood: "alegre", suggestions: [RestByMood(name: "Capitão Gancho",
                                                          type: "Pizzaria",
                                                          price: "$$",
                                                          rating: "4,6",
                                                          address: "Av. Fernando Simões Barbosa, 20 - Boa Viagem",
                                                          bairro: "Graças",
                                                          maskImage: UIImage(named: "capitaogancho-mask"),
                                                          backImage: UIImage(named: "capitaogancho-back"),
                                                          filters: [
                                                            
                                                          ],
                                                          drinks: false),
                                               RestByMood(name: "Babylon Station",
                                                          type: "Petiscos, Bar",
                                                          price: "$$-$$$",
                                                          rating: "4,5",
                                                          address: "Rua Nestor Silva 162, Santana",
                                                          bairro: "Graças",
                                                          maskImage: UIImage(named: "babylon-mask"),
                                                          backImage: UIImage(named: "babylon-back"),
                                                          filters: [
                                                            "Vegano",
                                                            "Vegetariano"
                                                          ],
                                                          drinks: true),
                                               RestByMood(name: "Mr Hoppy",
                                                          type: "Petiscos, Bar, Fast Food",
                                                          price: "$$-$$$",
                                                          rating: "4,5",
                                                          address: "R. Maria Carolina, 331, Boa Viagem",
                                                          bairro: "Graças",
                                                          maskImage: UIImage(named: "mrhoppy-mask"),
                                                          backImage: UIImage(named: "mrhoppy-back"),
                                                          filters: [
                                                            "Vegano",
                                                            "Vegetariano"
                                                          ],
                                                          drinks: true),
                                               RestByMood(name: "Parraxaxá",
                                                          type: "Buffet, Regional",
                                                          price: "$$-$$$",
                                                          rating: "4,5",
                                                          address: "Av. Fernando Simões Barbosa, 1200, Boa Viagem",
                                                          bairro: "Graças",
                                                          maskImage: UIImage(named: "parraxaxa-mask"),
                                                          backImage: UIImage(named: "parraxaxa-back"),
                                                          filters: [
                                                            "Vegano",
                                                            "Vegetariano"
                                                          ],
                                                          drinks: true),
                                               RestByMood(name: "The People Resto Bar",
                                                          type: "Petiscos, Bar",
                                                          price: "$$-$$$",
                                                          rating: "4,3",
                                                          address: "R. Confederação do Equador, 55, Graças",
                                                          bairro: "Graças",
                                                          maskImage: UIImage(named: "thepeople-mask"),
                                                          backImage: UIImage(named: "thepeople-back"),
                                                          filters: [
                                                            "Vegetariano",
                                                          ],
                                                          drinks: true),
                                               RestByMood(name: "081 Drink Bar",
                                                          type: "Bar, Drinks",
                                                          price: "$$",
                                                          rating: "4,0",
                                                          address: "R. João Dias Martins, 16, Boa Viagem",
                                                          bairro: "Graças",
                                                          maskImage: UIImage(named: "081-mask"),
                                                          backImage: UIImage(named: "081-back"),
                                                          filters: [
                                                            
                                                          ],
                                                          drinks: true),
                                               RestByMood(name: "Seu Tito",
                                                          type: "Brasileira, Drinks",
                                                          price: "$$-$$$",
                                                          rating: "4,5",
                                                          address: "Rua Igarassu, 104, Santana",
                                                          bairro: "Graças",
                                                          maskImage: UIImage(named: "seutito-mask"),
                                                          backImage: UIImage(named: "seutito-back"),
                                                          filters: [
                                                            
                                                          ],
                                                          drinks: true),
                                               RestByMood(name: "BRO Experience Tattoo Bar",
                                                          type: "Buffet, Regional",
                                                          price: "$$-$$$",
                                                          rating: "4,7",
                                                          address: "R. Fernando Lopes, 64",
                                                          bairro: "Graças",
                                                          maskImage: UIImage(named: "bro-mask"),
                                                          backImage: UIImage(named: "bro-back"),
                                                          filters: [
                                                            
                                                          ],
                                                          drinks: true),
                                               RestByMood(name: "Amada Lena",
                                                          type: "Bar",
                                                          price: "$$",
                                                          rating: "4,2",
                                                          address: "Avenida Visconde de Albuquerque, 411, Madalena",
                                                          bairro: "Graças",
                                                          maskImage: UIImage(named: "amadalena-mask"),
                                                          backImage: UIImage(named: "amadalena-back"),
                                                          filters: [
                                                            
                                                          ],
                                                          drinks: true),
                                               RestByMood(name: "Recanto Paraibano",
                                                          type: "Brasileira, Bar",
                                                          price: "$$-$$$",
                                                          rating: "4,6",
                                                          address: "Av. Dezessete de Agosto, 248 - Parnamirim",
                                                          bairro: "Graças",
                                                          maskImage: UIImage(named: "recantoparaibano-mask"),
                                                          backImage: UIImage(named: "recantoparaibano-back"),
                                                          filters: [
                                                            
                                                          ],
                                                          drinks: true)]
                ),
            // MARK: - mood: NOSTÁLGICO
            Mood(mood: "nostalgica", suggestions: [RestByMood(name: "Tio Armênio",
                                                              type: "Brasileira, Internacional, Contemporânea",
                                                              price: "$$-$$$",
                                                              rating: "4,6",
                                                              address: "R. Padre Carapuceiro, 777 - 423, Boa Viagem",
                                                              bairro: "Graças",
                                                              maskImage: UIImage(named: "tioarmenio-mask"),
                                                              backImage: UIImage(named: "tioarmenio-back"),
                                                              filters: [
                                                                "Vegano",
                                                                "Vegetariano"
                                                              ],
                                                              drinks: true),
                                                   RestByMood(name: "Ilha da Kosta",
                                                              type: "Brasileira, Frutos do Mar",
                                                              price: "$$-$$$",
                                                              rating: "4,6",
                                                              address: "R. Padre Bernadino Pessoa, 50 - Boa Viagem",
                                                              bairro: "Graças",
                                                              maskImage: UIImage(named: "ilha-mask"),
                                                              backImage: UIImage(named: "ilha-back"),
                                                              filters: [
                                                                "Vegetariano"
                                                              ],
                                                              drinks: true),
                                                   RestByMood(name: "Tio Pepe",
                                                              type: "Brasileira, Internacional, Contemporânea",
                                                              price: "$$-$$$",
                                                              rating: "4,6",
                                                              address: "Rua Almirante Tamandare 170 - Setúbal",
                                                              bairro: "Graças",
                                                              maskImage: UIImage(named: "tiopepe-mask"),
                                                              backImage: UIImage(named: "tiopepe-back"),
                                                              filters: [
                                                                "Vegetariano",
                                                              ],
                                                              drinks: true),
                                                   RestByMood(name: "Famiglia Giuliano",
                                                              type: "Italiana, Internacional, Contemporânea",
                                                              price: "$$$-$$$$",
                                                              rating: "4,7",
                                                              address: "Av. Eng. Domingos Ferreira, 3972, Boa Viagem",
                                                              bairro: "Graças",
                                                              maskImage: UIImage(named: "famiglia-mask"),
                                                              backImage: UIImage(named: "famiglia-back"),
                                                              filters: [
                                                                "Vegano",
                                                                "Vegetariano"
                                                              ],
                                                              drinks: true),
                                                   RestByMood(name: "Bargaço",
                                                              type: "Brasileira, Frutos do Mar",
                                                              price: "$$$-$$$$",
                                                              rating: "4,6",
                                                              address: "Av. Antônio de Goes, 62, Pina",
                                                              bairro: "Graças",
                                                              maskImage: UIImage(named: "bargaco-mask"),
                                                              backImage: UIImage(named: "bargaco-back"),
                                                              filters: [
                                                                
                                                              ],
                                                              drinks: true)]
                ),
            // MARK: - mood: DANÇANTE
            Mood(mood: "dancante", suggestions: [
                                                 RestByMood(name: "The Match Srike Pub",
                                                            type: "Bar, Pub",
                                                            price: "$$-$$$",
                                                            rating: "4,5",
                                                            address: "Av. Eng. Domingos Ferreira, 1950, Boa Viagem",
                                                            bairro: "Graças",
                                                            maskImage: UIImage(named: "matchclub-mask"),
                                                            backImage: UIImage(named: "matchclub-back"),
                                                            filters: [
                                                                
                                                            ],
                                                            drinks: true),
                                                 RestByMood(name: "Pajubar",
                                                            type: "Americana, Churrascaria",
                                                            price: "$$-$$$",
                                                            rating: "4,0",
                                                            address: "Av. Manoel Borba, 693, Boa Vista",
                                                            bairro: "Graças",
                                                            maskImage: UIImage(named: "pajubar-mask"),
                                                            backImage: UIImage(named: "pajubar-back"),
                                                            filters: [
                                                                "Vegano",
                                                                "Vegetariano"
                                                            ],
                                                            drinks: true),
                                                 RestByMood(name: "Bar do Céu",
                                                            type: "Bar",
                                                            price: "$$",
                                                            rating: "4,2",
                                                            address: "R. das Ninfas, 84 - Soledade",
                                                            bairro: "Graças",
                                                            maskImage: UIImage(named: "bardoceu-mask"),
                                                            backImage: UIImage(named: "bardoceu-back"),
                                                            filters: [
                                                                
                                                            ],
                                                            drinks: true),
                                                 RestByMood(name: "Liamba",
                                                            type: "Petiscos, Bar",
                                                            price: "$$",
                                                            rating: "4,5",
                                                            address: "R. Fernando Lopes, 78 - Graças",
                                                            bairro: "Graças",
                                                            maskImage: UIImage(named: "liamba-mask"),
                                                            backImage: UIImage(named: "liamba-back"),
                                                            filters: [
                                                                
                                                            ],
                                                            drinks: true),
                                                 RestByMood(name: "Burburinho",
                                                            type: "Brasileira, Bar",
                                                            price: "$$",
                                                            rating: "4,2",
                                                            address: "R. Vigário Tenório, 185, Recife Antigo",
                                                            bairro: "Graças",
                                                            maskImage: UIImage(named: "burburinho-mask"),
                                                            backImage: UIImage(named: "burburinho-back"),
                                                            filters: [
                                                                "Vegano",
                                                                "Vegetariano"
                                                            ],
                                                            drinks: true)]
                ),
            // MARK: - mood: NATURAL
            Mood(mood: "natural", suggestions: [RestByMood(name: "ARVO",
                                                           type: "Brasileira",
                                                           price: "$$$",
                                                           rating: "4,7",
                                                           address: "R. Djalma Farias, 170, Torreão",
                                                           bairro: "Graças",
                                                           maskImage: UIImage(named: "arvo-mask"),
                                                           backImage: UIImage(named: "arvo-back"),
                                                           filters: [
                                                            "Vegano",
                                                            "Vegetariano"
                                                           ],
                                                           drinks: true),
                                                RestByMood(name: "Amanita",
                                                           type: "Hamburgueria Vegana",
                                                           price: "$$$",
                                                           rating: "4,6",
                                                           address: "R. Guimarães Peixoto, 37 - Casa Amarela",
                                                           bairro: "Graças",
                                                           maskImage: UIImage(named: "amanita-mask"),
                                                           backImage: UIImage(named: "amanita-back"),
                                                           filters: [
                                                            "Vegano",
                                                            "Vegetariano"
                                                           ],
                                                           drinks: true),
                                                RestByMood(name: "Reteteu Comida Honesta",
                                                           type: "Brasileira",
                                                           price: "$$-$$$",
                                                           rating: "4,7",
                                                           address: "R. Prof. Otávio de Freitas, 256, Encruzilhada",
                                                           bairro: "Graças",
                                                           maskImage: UIImage(named: "reteteu-mask"),
                                                           backImage: UIImage(named: "reteteu-back"),
                                                           filters: [
                                                            "Vegano",
                                                            "Vegetariano"
                                                           ],
                                                           drinks: true),
                                                RestByMood(name: "Papacapim",
                                                           type: "Italiana, Brasileira",
                                                           price: "$$",
                                                           rating: "4,5",
                                                           address: "Av. Rui Barbosa, 1397 - Graças",
                                                           bairro: "Graças",
                                                           maskImage: UIImage(named: "papacapim-mask"),
                                                           backImage: UIImage(named: "papacapim-back"),
                                                           filters: [
                                                            "Vegano",
                                                            "Vegetariano"
                                                           ],
                                                           drinks: true),
                                                RestByMood(name: "Garden Comida com Afeto",
                                                           type: "Brasileira",
                                                           price: "$$",
                                                           rating: "4,3",
                                                           address: "Av. Conselheiro Rosa e Silva, 1405 - Aflitos",
                                                           bairro: "Graças",
                                                           maskImage: UIImage(named: "garden-mask"),
                                                           backImage: UIImage(named: "garden-back"),
                                                           filters: [
                                                            "Vegano",
                                                            "Vegetariano"
                                                           ],
                                                           drinks: false),
                                                RestByMood(name: "Papaya Verde",
                                                           type: "Libanesa, Israelita",
                                                           price: "$$-$$$",
                                                           rating: "4,6",
                                                           address: "R. Santo Elías, 409 - Espinheiro",
                                                           bairro: "Graças",
                                                           maskImage: UIImage(named: "papayaverde-mask"),
                                                           backImage: UIImage(named: "papayaverde-back"),
                                                           filters: [
                                                            "Vegano",
                                                            "Vegetariano"
                                                           ],
                                                           drinks: false),
                                                RestByMood(name: "Cajá",
                                                           type: "Brasileira, Contemporânea",
                                                           price: "$$-$$$",
                                                           rating: "4,6",
                                                           address: "R. Carneiro Viléla, 648 - Aflitos",
                                                           bairro: "Graças",
                                                           maskImage: UIImage(named: "caja-mask"),
                                                           backImage: UIImage(named: "caja-back"),
                                                           filters: [
                                                            "Vegano",
                                                            "Vegetariano"
                                                           ],
                                                           drinks: true),
                                                RestByMood(name: "Manu Tenório Culinária Saudável",
                                                           type: "Brasileira, Café, Saudável",
                                                           price: "$$-$$$",
                                                           rating: "5,0",
                                                           address: "Avenida Rui Barbosa 1503",
                                                           bairro: "Graças",
                                                           maskImage: UIImage(named: "manutenorio-mask"),
                                                           backImage: UIImage(named: "manutenorio-back"),
                                                           filters: [
                                                            "Vegano",
                                                            "Vegetariano"
                                                           ],
                                                           drinks: false),
                                                RestByMood(name: "São Pedro Marisqueira",
                                                           type: "Frutos do Mar",
                                                           price: "$$-$$$",
                                                           rating: "4,6",
                                                           address: "Bairro se - R. Felipe Camarão, 33 - São José",
                                                           bairro: "Graças",
                                                           maskImage: UIImage(named: "saopedro-mask"),
                                                           backImage: UIImage(named: "saopedro-back"),
                                                           filters: [
                                                            "Vegano",
                                                            "Vegetariano"
                                                           ],
                                                           drinks: true),
                                                RestByMood(name: "Beijupirá",
                                                           type: "Frutos do Mar",
                                                           price: "$$$-$$$$",
                                                           rating: "4,5",
                                                           address: "R. do Amparo, 148 - Carmo",
                                                           bairro: "Graças",
                                                           maskImage: UIImage(named: "beijupira-mask"),
                                                           backImage: UIImage(named: "beijupira-back"),
                                                           filters: [
                                                            "Vegano",
                                                            "Vegetariano"
                                                           ],
                                                           drinks: true)]
                ),
            // MARK: - mood: ESPIRITUOSO
            Mood(mood: "espirituosa", suggestions: [RestByMood(name: "Melhor Cantinho da Cidade",
                                                               type: "Coffee Shop",
                                                               price: "$",
                                                               rating: "4,6",
                                                               address: "R. Azeredo Coutinho, 10 - Várzea",
                                                               bairro: "Graças",
                                                               maskImage: UIImage(named: "melhorcantinho-mask"),
                                                               backImage: UIImage(named: "melhorcantinho-back"),
                                                               filters: [
                                                                "Vegano",
                                                                "Vegetariano"
                                                               ],
                                                               drinks: false),
                                                    RestByMood(name: "Borsoi",
                                                               type: "Coffee Shop",
                                                               price: "$$",
                                                               rating: "4,6",
                                                               address: "Rua Artur Muniz 82, Boa Viagem",
                                                               bairro: "Graças",
                                                               maskImage: UIImage(named: "borsoi-mask"),
                                                               backImage: UIImage(named: "borsoi-back"),
                                                               filters: [
                                                                "Vegano",
                                                                "Vegetariano"
                                                               ],
                                                               drinks: false),
                                                    RestByMood(name: "A Vida é Bela",
                                                               type: "Coffee Shop",
                                                               price: "$$",
                                                               rating: "4,6",
                                                               address: "R. Francisco Lacerda, 394 - Várzea",
                                                               bairro: "Graças",
                                                               maskImage: UIImage(named: "avidaebela-mask"),
                                                               backImage: UIImage(named: "avidaebela-back"),
                                                               filters: [
                                                                "Vegano",
                                                                "Vegetariano"
                                                               ],
                                                               drinks: false)]
                ),
            // MARK: - mood: CAÓTICO
            Mood(mood: "caotica", suggestions: [RestByMood(name: "Liamba",
                                                           type: "Petiscos, Bar",
                                                           price: "$$",
                                                           rating: "4,5",
                                                           address: "R. Fernando Lopes, 78 - Graças",
                                                           bairro: "Graças",
                                                           maskImage: UIImage(named: "liamba-mask"),
                                                           backImage: UIImage(named: "liamba-back"),
                                                           filters: [
                                                            
                                                           ],
                                                           drinks: true),
                                                RestByMood(name: "Vaporetto",
                                                           type: "Bar",
                                                           price: "$$-$$$",
                                                           rating: "4,3",
                                                           address: "R. Leopoldino Silva, 100 - Santana",
                                                           bairro: "Graças",
                                                           maskImage: UIImage(named: "vaporetto-mask"),
                                                           backImage: UIImage(named: "vaporetto-back"),
                                                           filters: [
                                                            
                                                           ],
                                                           drinks: true),
                                                RestByMood(name: "Casa Bacurau",
                                                           type: "Bar",
                                                           price: "$$",
                                                           rating: "4,3",
                                                           address: "R. Cap. Lima, 100 - Santo Amaro",
                                                           bairro: "Graças",
                                                           maskImage: UIImage(named: "bacurau-mask"),
                                                           backImage: UIImage(named: "bacurau-back"),
                                                           filters: [
                                                            
                                                           ],
                                                           drinks: true),
                                                RestByMood(name: "Bar do Cuscuz",
                                                           type: "Brasileira, Bar",
                                                           price: "$$-$$$",
                                                           rating: "4,1",
                                                           address: "Av. Fernando Simões Barbosa, 170 - Boa Viagem",
                                                           bairro: "Graças",
                                                           maskImage: UIImage(named: "bardocuscuz-mask"),
                                                           backImage: UIImage(named: "bardocuscuz-back"),
                                                           filters: [
                                                            
                                                           ],
                                                           drinks: false),
                                                RestByMood(name: "Faminto's",
                                                           type: "Brasileira",
                                                           price: "$$-$$$",
                                                           rating: "4,2",
                                                           address: "R. Sant'Anna, 12 - Casa Forte",
                                                           bairro: "Graças",
                                                           maskImage: UIImage(named: "famintos-mask"),
                                                           backImage: UIImage(named: "famintos-back"),
                                                           filters: [
                                                            "Vegano",
                                                            "Vegetariano"
                                                           ],
                                                           drinks: false)]
                ),
            // MARK: - mood: ELEGANTE
            Mood(mood: "elegante", suggestions: [RestByMood(name: "Vetro Ristrot e Fusion Lounge",
                                                            type: "Italiana, Francesa",
                                                            price: "$$$$",
                                                            rating: "4,7",
                                                            address: "Av. Conselheiro Aguiar, 916 - Boa Viagem",
                                                            bairro: "Graças",
                                                            maskImage: UIImage(named: "vetro-mask"),
                                                            backImage: UIImage(named: "vetro-back"),
                                                            filters: [
                                                                "Vegano",
                                                                "Vegetariano"
                                                            ],
                                                            drinks: true),
                                                 RestByMood(name: "Vasto",
                                                            type: "Japonesa, Frutos do Mar",
                                                            price: "$$$$",
                                                            rating: "4,9",
                                                            address: "1° Piso Shopping Recife, R. Padre Carapuceiro, 777 - Boa Viagem",
                                                            bairro: "Graças",
                                                            maskImage: UIImage(named: "vasto-mask"),
                                                            backImage: UIImage(named: "vasto-back"),
                                                            filters: [
                                                                "Vegano",
                                                                "Vegetariano"
                                                            ],
                                                            drinks: true),
                                                 RestByMood(name: "Casa do Vinho Al Mare",
                                                            type: "Wine Bar",
                                                            price: "$$$$",
                                                            rating: "4,1",
                                                            address: "R. Manuel Borba, 338 - Carmo",
                                                            bairro: "Graças",
                                                            maskImage: UIImage(named: "casadovinho-mask"),
                                                            backImage: UIImage(named: "casadovinho-back"),
                                                            filters: [
                                                                "Vegetariano"
                                                            ],
                                                            drinks: true),
                                                 RestByMood(name: "Bargaço",
                                                            type: "Brasileira, Frutos do Mar",
                                                            price: "$$$-$$$$",
                                                            rating: "4,6",
                                                            address: "Av. Antônio de Goes, 62, Pina",
                                                            bairro: "Graças",
                                                            maskImage: UIImage(named: "bargaco-mask"),
                                                            backImage: UIImage(named: "bargaco-back"),
                                                            filters: [
                                                                
                                                            ],
                                                            drinks: true),
                                                 RestByMood(name: "The Black Angus",
                                                            type: "Brasileira, Steakhouse, Wine Bar",
                                                            price: "$$$-$$$$",
                                                            rating: "4,3",
                                                            address: "R. França Pereira, 146 - Boa Viagem",
                                                            bairro: "Graças",
                                                            maskImage: UIImage(named: "blackangus-mask"),
                                                            backImage: UIImage(named: "blackangus-back"),
                                                            filters: [
                                                                "Vegano",
                                                                "Vegetariano"
                                                            ],
                                                            drinks: true),
                                                 RestByMood(name: "Tio Armênio",
                                                            type: "Brasileira, Internacional, Contemporânea",
                                                            price: "$$-$$$",
                                                            rating: "4,6",
                                                            address: "R. Padre Carapuceiro, 777 - 423, Boa Viagem",
                                                            bairro: "Graças",
                                                            maskImage: UIImage(named: "tioarmenio-mask"),
                                                            backImage: UIImage(named: "tioarmenio-back"),
                                                            filters: [
                                                                "Vegano",
                                                                "Vegetariano"
                                                            ],
                                                            drinks: true),
                                                 RestByMood(name: "Papacapim",
                                                            type: "Italiana, Brasileira",
                                                            price: "$$",
                                                            rating: "4,5",
                                                            address: "Av. Rui Barbosa, 1397 - Graças",
                                                            bairro: "Graças",
                                                            maskImage: UIImage(named: "papacapim-mask"),
                                                            backImage: UIImage(named: "papacapim-back"),
                                                            filters: [
                                                                "Vegano",
                                                                "Vegetariano"
                                                            ],
                                                            drinks: true),
                                                 RestByMood(name: "La Pecora Nera",
                                                            type: "Italiana",
                                                            price: "$$$$",
                                                            rating: "4,5",
                                                            address: "Praça de Casa Forte, 505 - Casa Forte",
                                                            bairro: "Graças",
                                                            maskImage: UIImage(named: "pecoranera-mask"),
                                                            backImage: UIImage(named: "pecoranera-back"),
                                                            filters: [
                                                                "Vegano",
                                                                "Vegetariano"
                                                            ],
                                                            drinks: true),
                                                 RestByMood(name: "Nikko Japanese Fusion",
                                                            type: "Japonesa",
                                                            price: "$$$-$$$$",
                                                            rating: "4,3",
                                                            address: "Av. Conselheiro Aguiar, 1712 - Boa Viagem",
                                                            bairro: "Graças",
                                                            maskImage: UIImage(named: "nikko-mask"),
                                                            backImage: UIImage(named: "nikko-back"),
                                                            filters: [
                                                                
                                                            ],
                                                            drinks: true),
                                                 RestByMood(name: "Quina do Futuro",
                                                            type: "Japonesa",
                                                            price: "$$$$",
                                                            rating: "4,6",
                                                            address: "R. Xavier Marques, 134 - Aflitos",
                                                            bairro: "Graças",
                                                            maskImage: UIImage(named: "quina-mask"),
                                                            backImage: UIImage(named: "quina-back"),
                                                            filters: [
                                                                "Vegano",
                                                                "Vegetariano"
                                                            ],
                                                            drinks: true),
                                                 RestByMood(name: "Sumô Sushi Bar",
                                                            type: "Japonesa",
                                                            price: "$$-$$$",
                                                            rating: "4,5",
                                                            address: "R. Xavier Marques, 87 - Graças",
                                                            bairro: "Graças",
                                                            maskImage: UIImage(named: "sumo-mask"),
                                                            backImage: UIImage(named: "bardocabo-back"),
                                                            filters: [
                                                                "Vegano",
                                                                "Vegetariano"
                                                            ],
                                                            drinks: true)]
                )
        ]
    }
}
