//
//  RestByMood+Restaurants.swift
//  Vibefy
//
//  Created by Guilherme Souza on 15/09/22.
//

// MARK: - RestByMood + Restaurants

import Foundation

extension RestByMood {
    
    static func restaurants() -> [RestByMood] {
        
        return [
            
            // MARK: - mood: INTROSPECTIVO
            
            RestByMood(mood: "introspectivo",
                       name: "Café 81",
                       type: "Coffee Shop",
                       price: "$$",
                       rating: "4,7",
                       address: "R. das Creoulas, 55A - Graças",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: false),
            
            RestByMood(mood: "introspectivo",
                       name: "Versado",
                       type: "Coffee Shop",
                       price: "$$",
                       rating: "4,9",
                       address: "R. do Cupim, 259 - Graças",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        
                       ],
                       drinks: false),
            RestByMood(mood: "introspectivo",
                       name: "Lala Café & Cozinha Afetiva",
                       type: "Coffee Shop",
                       price: "$$-$$$",
                       rating: "4,4",
                       address: "R. Amélia, 470 - Graças",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: false),
            RestByMood(mood: "introspectivo",
                       name: "Borsoi",
                       type: "Coffee Shop",
                       price: "$$",
                       rating: "4,6",
                       address: "Rua Artur Muniz 82, Boa Viagem",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: false),
            RestByMood(mood: "introspectivo",
                       name: "Galo Padeiro",
                       type: "Coffee Shop, Diner",
                       price: "$$-$$$",
                       rating: "4,6",
                       address: "R. Cap. Lima, 82 - Santo Amaro",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: false),
            RestByMood(mood: "introspectivo",
                       name: "Café mais prosa",
                       type: "Coffee Shop",
                       price: "$",
                       rating: "4,6",
                       address: "Rua Barão de Itamaracá 284, Loja 4",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        
                       ],
                       drinks: false),
            
            // MARK: - mood: VIBRANTE
            
            RestByMood(mood: "vibrante",
                       name: "Porpino’s Burger",
                       type: "Hamburgueria",
                       price: "$$",
                       rating: "4,8",
                       address: "Av. Conselheiro Aguiar, 1275 - Boa Viagem",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "vibrante",
                       name: "Terraço Carvalheira",
                       type: "Brasileira, Bar, Churrasco",
                       price: "$$-$$$$",
                       rating: "4,4",
                       address: "R. Padre Carapuceiro, 777 - Edifício Garagem (Cobertura B4 - Boa Viagem)",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        
                       ],
                       drinks: true),
            
            // MARK: - mood: TRANQUILO
            
            RestByMood(mood: "tranquilo",
                       name: "Borsoi",
                       type: "Coffee Shop",
                       price: "$$",
                       rating: "4,6",
                       address: "Rua Artur Muniz 82, Boa Viagem",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: false),
            RestByMood(mood: "tranquilo",
                       name: "Tokyo's Cafe",
                       type: "Coffee Shop",
                       price: "$$-$$$",
                       rating: "4,6",
                       address: "Av. Dr. Malaquias, 79 - Graças",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: false),
            RestByMood(mood: "tranquilo",
                       name: "Amanita",
                       type: "Hamburgueria Vegana",
                       price: "$$$",
                       rating: "4,6",
                       address: "R. Guimarães Peixoto, 37 - Casa Amarela",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "tranquilo",
                       name: "Melhor Cantinho da Cidade",
                       type: "Coffee Shop",
                       price: "$",
                       rating: "4,6",
                       address: "R. Azeredo Coutinho, 10 - Várzea",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: false),
            RestByMood(mood: "tranquilo",
                       name: "A Vida é Bela",
                       type: "Coffee Shop",
                       price: "$$",
                       rating: "4,6",
                       address: "R. Francisco Lacerda, 394 - Várzea",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: false),
            RestByMood(mood: "tranquilo",
                       name: "Manu Tenório Culinária Saudável",
                       type: "Brasileira, Café, Saudável",
                       price: "$$-$$$",
                       rating: "5,0",
                       address: "Avenida Rui Barbosa 1503",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: false),
            RestByMood(mood: "tranquilo",
                       name: "Vila Amizade Padaria Artesanal",
                       type: "Padaria",
                       price: "$$$",
                       rating: "4,6",
                       address: "Rua Da Amizade, 54, Graças",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegetariano"
                       ],
                       drinks: false),
            RestByMood(mood: "tranquilo",
                       name: "O Pátio",
                       type: "Coffee Shop",
                       price: "$$",
                       rating: "4,5",
                       address: "Av. Rui Barbosa, 141 - Graças",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        
                       ],
                       drinks: false),
            RestByMood(mood: "tranquilo",
                       name: "Café com Dengo",
                       type: "Coffee Shop",
                       price: "$$-$$$",
                       rating: "4,5",
                       address: "R. Desembargador Martins Pereira, 45, Rosarinho",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: false),
            // MARK: - mood: ROMÂNTICO
            
            RestByMood(mood: "romântico",
                       name: "Tokyo's Cafe",
                       type: "Coffee Shop",
                       price: "$$-$$$",
                       rating: "4,6",
                       address: "Av. Dr. Malaquias, 79 - Graças",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: false),
            RestByMood(mood: "romântico",
                       name: "La Pecora Nera",
                       type: "Italiana",
                       price: "$$$$",
                       rating: "4,5",
                       address: "Praça de Casa Forte, 505 - Casa Forte",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "romântico",
                       name: "La Pecora Nera",
                       type: "Italiana",
                       price: "$$$$",
                       rating: "4,5",
                       address: "Praça de Casa Forte, 505 - Casa Forte",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "romântico",
                       name: "La Tratoria",
                       type: "Italiana, Massas",
                       price: "$$-$$$",
                       rating: "4,5",
                       address: "Rua Carlos Pereira Falcão 334 - Boa Viagem",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano",
                        "Saudável"
                       ],
                       drinks: true),
            RestByMood(mood: "romântico",
                       name: "Lupi Pizzeria",
                       type: "Italiana, Pizza",
                       price: "$$-$$$",
                       rating: "5,0",
                       address: "R. José Domingues da Silva, 238 - Boa Viagem",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "romântico",
                       name: "Chiwake",
                       type: "Peruana, Latina, Frutos do Mar",
                       price: "$$$$",
                       rating: "4,5",
                       address: "R. da Hora, 820 - Espinheiro",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "romântico",
                       name: "Jojoo Creative Sushi",
                       type: "Japonesa, Frutos do Mar, Sushi",
                       price: "$$$$",
                       rating: "4,5",
                       address: "Av. Conselheiro Aguiar, 802 - Boa Viagem",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "romântico",
                       name: "Anjo Solto",
                       type: "Francesa, Brasileira, Contemporânea",
                       price: "$$-$$$",
                       rating: "4,5",
                       address: "R. Herculano Bandeira, 513 - Pina",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano",
                        "Saudável"
                       ],
                       drinks: true),
            RestByMood(mood: "romântico",
                       name: "Le Chef Bistro",
                       type: "Francesa",
                       price: "$$$$",
                       rating: "4,5",
                       address: "Av. Eng. Domingos Ferreira, 1097 - Boa Viagem",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano",
                        "Saudável",
                        "Opções sem Gluten"
                       ],
                       drinks: true),
            
            // MARK: - mood: INTENSO
            
            RestByMood(mood: "intenso",
                       name: "Rock & Ribs",
                       type: "Americana, Churrascaria",
                       price: "$$-$$$",
                       rating: "4,5",
                       address: "Av. Alfredo Lisboa, S/N - Marco Zero",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "intenso",
                       name: "Outback Steakhouse",
                       type: "Australiana, Churrascaria",
                       price: "$$-$$$",
                       rating: "4,6",
                       address: "R. Padre Carapuceiro, 777 - Boa Viagem",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "intenso",
                       name: "Carranca Bar",
                       type: "Argentina, Bar",
                       price: "$$",
                       rating: "4,5",
                       address: "Av. 17 de agosto, 1778",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        
                       ],
                       drinks: true),
            RestByMood(mood: "intenso",
                       name: "Babylon Station",
                       type: "Petiscos, Bar",
                       price: "$$-$$$",
                       rating: "4,5",
                       address: "Rua Nestor Silva 162, Santana",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "intenso",
                       name: "Vaporetto",
                       type: "Bar",
                       price: "$$-$$$",
                       rating: "4,3",
                       address: "R. Leopoldino Silva, 100 - Santana",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        
                       ],
                       drinks: true),
            RestByMood(mood: "intenso",
                       name: "Barchef Boteco",
                       type: "Bar",
                       price: "$$-$$$",
                       rating: "4,5",
                       address: "Av. Conselheiro Aguiar, 2814 - Boa Viagem",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        
                       ],
                       drinks: true),
            RestByMood(mood: "intenso",
                       name: "Liamba",
                       type: "Petiscos, Bar",
                       price: "$$",
                       rating: "4,5",
                       address: "R. Fernando Lopes, 78 - Graças",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        
                       ],
                       drinks: true),
            // MARK: - mood: PRAIEIRO
            RestByMood(mood: "praieiro",
                       name: "Entre Amigos Praia",
                       type: "Brasileira, Frutos do Mar",
                       price: "$$$",
                       rating: "4,6",
                       address: "Av. Boa Viagem, 760 - Boa Viagem",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "praieiro",
                       name: "Barraca da Edite",
                       type: "Petiscos, Drinks",
                       price: "$$",
                       rating: "5",
                       address: "Av. Boa Viagem, 760 - Boa Viagem (proximidades)",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "praieiro",
                       name: "Rota do Mar",
                       type: "Frutos do Mar",
                       price: "$$-$$$",
                       rating: "4,6",
                       address: "R. José de Souza Marmelo, 112, Barra de Jangada",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        
                       ],
                       drinks: true),
            RestByMood(mood: "praieiro",
                       name: "Bar do Cabo",
                       type: "Frutos do Mar",
                       price: "$$",
                       rating: "4,7",
                       address: "R. Nanuque, 37 - Brasília Teimosa",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        
                       ],
                       drinks: false),
            RestByMood(mood: "praieiro",
                       name: "Seu Tito Praia",
                       type: "Brasileira",
                       price: "$$",
                       rating: "4,5",
                       address: "R. Artur Muniz, 82 - Boa Viagem",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        
                       ],
                       drinks: true),
            // MARK: - mood: ALEGRE
            RestByMood(mood: "alegre",
                       name: "Capitão Gancho",
                       type: "Pizzaria",
                       price: "$$",
                       rating: "4,6",
                       address: "Av. Fernando Simões Barbosa, 20 - Boa Viagem",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        
                       ],
                       drinks: false),
            RestByMood(mood: "alegre",
                       name: "Babylon Station",
                       type: "Petiscos, Bar",
                       price: "$$-$$$",
                       rating: "4,5",
                       address: "Rua Nestor Silva 162, Santana",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "alegre",
                       name: "Mr Hoppy",
                       type: "Petiscos, Bar, Fast Food",
                       price: "$$-$$$",
                       rating: "4,5",
                       address: "R. Maria Carolina, 331, Boa Viagem",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "alegre",
                       name: "Parraxaxá",
                       type: "Buffet, Regional",
                       price: "$$-$$$",
                       rating: "4,5",
                       address: "Av. Fernando Simões Barbosa, 1200, Boa Viagem",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "alegre",
                       name: "The People Resto Bar",
                       type: "Petiscos, Bar",
                       price: "$$-$$$",
                       rating: "4,3",
                       address: "R. Confederação do Equador, 55, Graças",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegetariano",
                       ],
                       drinks: true),
            RestByMood(mood: "alegre",
                       name: "081 Drink Bar",
                       type: "Bar, Drinks",
                       price: "$$",
                       rating: "4,0",
                       address: "R. João Dias Martins, 16, Boa Viagem",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        
                       ],
                       drinks: true),
            RestByMood(mood: "alegre",
                       name: "Seu Tito",
                       type: "Brasileira, Drinks",
                       price: "$$-$$$",
                       rating: "4,5",
                       address: "Rua Igarassu, 104, Santana",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        
                       ],
                       drinks: true),
            RestByMood(mood: "alegre",
                       name: "BRO Experience Tattoo Bar",
                       type: "Buffet, Regional",
                       price: "$$-$$$",
                       rating: "4,7",
                       address: "R. Fernando Lopes, 64",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        
                       ],
                       drinks: true),
            RestByMood(mood: "alegre",
                       name: "Amada Lena",
                       type: "Bar",
                       price: "$$",
                       rating: "4,2",
                       address: "Avenida Visconde de Albuquerque, 411, Madalena",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        
                       ],
                       drinks: true),
            RestByMood(mood: "alegre",
                       name: "Recanto Paraibano",
                       type: "Brasileira, Bar",
                       price: "$$-$$$",
                       rating: "4,6",
                       address: "Av. Dezessete de Agosto, 248 - Parnamirim",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        
                       ],
                       drinks: true),
            // MARK: - mood: NOSTÁLGICO
            RestByMood(mood: "nostálgico",
                       name: "Tio Armênio",
                       type: "Brasileira, Internacional, Contemporânea",
                       price: "$$-$$$",
                       rating: "4,6",
                       address: "R. Padre Carapuceiro, 777 - 423, Boa Viagem",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "nostálgico",
                       name: "Ilha da Kosta",
                       type: "Brasileira, Frutos do Mar",
                       price: "$$-$$$",
                       rating: "4,6",
                       address: "R. Padre Bernadino Pessoa, 50 - Boa Viagem",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "nostálgico",
                       name: "Tio Pepe",
                       type: "Brasileira, Internacional, Contemporânea",
                       price: "$$-$$$",
                       rating: "4,6",
                       address: "Rua Almirante Tamandare 170 - Setúbal",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegetariano",
                       ],
                       drinks: true),
            RestByMood(mood: "nostálgico",
                       name: "Famiglia Giuliano",
                       type: "Italiana, Internacional, Contemporânea",
                       price: "$$$-$$$$",
                       rating: "4,7",
                       address: "Av. Eng. Domingos Ferreira, 3972, Boa Viagem",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "nostálgico",
                       name: "Bargaço",
                       type: "Brasileira, Frutos do Mar",
                       price: "$$$-$$$$",
                       rating: "4,6",
                       address: "Av. Antônio de Goes, 62, Pina",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        
                       ],
                       drinks: true),
            // MARK: - mood: DANÇANTE
            RestByMood(mood: "dançante",
                       name: "Rock & Ribs",
                       type: "Americana, Churrascaria",
                       price: "$$-$$$",
                       rating: "4,5",
                       address: "Av. Alfredo Lisboa, S/N - Marco Zero",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "dançante",
                       name: "The Match Srike Pub",
                       type: "Bar, Pub",
                       price: "$$-$$$",
                       rating: "4,5",
                       address: "Av. Eng. Domingos Ferreira, 1950, Boa Viagem",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        
                       ],
                       drinks: true),
            RestByMood(mood: "dançante",
                       name: "Pajubar",
                       type: "Americana, Churrascaria",
                       price: "$$-$$$",
                       rating: "4,0",
                       address: "Av. Manoel Borba, 693, Boa Vista",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "dançante",
                       name: "Bar do Céu",
                       type: "Bar",
                       price: "$$",
                       rating: "4,2",
                       address: "R. das Ninfas, 84 - Soledade",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        
                       ],
                       drinks: true),
            RestByMood(mood: "dançante",
                       name: "Liamba",
                       type: "Petiscos, Bar",
                       price: "$$",
                       rating: "4,5",
                       address: "R. Fernando Lopes, 78 - Graças",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        
                       ],
                       drinks: true),
            RestByMood(mood: "dançante",
                       name: "Burburinho",
                       type: "Brasileira, Bar",
                       price: "$$",
                       rating: "4,2",
                       address: "R. Vigário Tenório, 185, Recife Antigo",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            // MARK: - mood: NATURAL
            RestByMood(mood: "natural",
                       name: "ARVO",
                       type: "Brasileira",
                       price: "$$$",
                       rating: "4,7",
                       address: "R. Djalma Farias, 170, Torreão",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "natural",
                       name: "Amanita",
                       type: "Hamburgueria Vegana",
                       price: "$$$",
                       rating: "4,6",
                       address: "R. Guimarães Peixoto, 37 - Casa Amarela",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "natural",
                       name: "Reteteu Comida Honesta",
                       type: "Brasileira",
                       price: "$$-$$$",
                       rating: "4,7",
                       address: "R. Prof. Otávio de Freitas, 256, Encruzilhada",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "natural",
                       name: "Papacapim",
                       type: "Italiana, Brasileira",
                       price: "$$",
                       rating: "4,5",
                       address: "Av. Rui Barbosa, 1397 - Graças",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "natural",
                       name: "Garden Comida com Afeto",
                       type: "Brasileira",
                       price: "$$",
                       rating: "4,3",
                       address: "Av. Conselheiro Rosa e Silva, 1405 - Aflitos",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: false),
            RestByMood(mood: "natural",
                       name: "Papaya Verde",
                       type: "Libanesa, Israelita",
                       price: "$$-$$$",
                       rating: "4,6",
                       address: "R. Santo Elías, 409 - Espinheiro",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: false),
            RestByMood(mood: "natural",
                       name: "Cajá",
                       type: "Brasileira, Contemporânea",
                       price: "$$-$$$",
                       rating: "4,6",
                       address: "R. Carneiro Viléla, 648 - Aflitos",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "natural",
                       name: "Manu Tenório Culinária Saudável",
                       type: "Brasileira, Café, Saudável",
                       price: "$$-$$$",
                       rating: "5,0",
                       address: "Avenida Rui Barbosa 1503",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: false),
            RestByMood(mood: "natural",
                       name: "São Pedro Marisqueira",
                       type: "Frutos do Mar",
                       price: "$$-$$$",
                       rating: "4,6",
                       address: "Bairro se - R. Felipe Camarão, 33 - São José",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "natural",
                       name: "Beijupirá",
                       type: "Frutos do Mar",
                       price: "$$$-$$$$",
                       rating: "4,5",
                       address: "R. do Amparo, 148 - Carmo",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            // MARK: - mood: ESPIRITUOSO
            RestByMood(mood: "espirituoso",
                       name: "Melhor Cantinho da Cidade",
                       type: "Coffee Shop",
                       price: "$",
                       rating: "4,6",
                       address: "R. Azeredo Coutinho, 10 - Várzea",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: false),
            RestByMood(mood: "espirituoso",
                       name: "Borsoi",
                       type: "Coffee Shop",
                       price: "$$",
                       rating: "4,6",
                       address: "Rua Artur Muniz 82, Boa Viagem",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: false),
            RestByMood(mood: "espirituoso",
                       name: "A Vida é Bela",
                       type: "Coffee Shop",
                       price: "$$",
                       rating: "4,6",
                       address: "R. Francisco Lacerda, 394 - Várzea",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: false),
            // MARK: - mood: CAÓTICO
            RestByMood(mood: "caótico",
                       name: "Liamba",
                       type: "Petiscos, Bar",
                       price: "$$",
                       rating: "4,5",
                       address: "R. Fernando Lopes, 78 - Graças",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        
                       ],
                       drinks: true),
            RestByMood(mood: "caótico",
                       name: "Vaporetto",
                       type: "Bar",
                       price: "$$-$$$",
                       rating: "4,3",
                       address: "R. Leopoldino Silva, 100 - Santana",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        
                       ],
                       drinks: true),
            RestByMood(mood: "caótico",
                       name: "Casa Bacurau",
                       type: "Bar",
                       price: "$$",
                       rating: "4,3",
                       address: "R. Cap. Lima, 100 - Santo Amaro",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        
                       ],
                       drinks: true),
            RestByMood(mood: "caótico",
                       name: "Bar do Cuscuz",
                       type: "Brasileira, Bar",
                       price: "$$-$$$",
                       rating: "4,1",
                       address: "Av. Fernando Simões Barbosa, 170 - Boa Viagem",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        
                       ],
                       drinks: false),
            RestByMood(mood: "caótico",
                       name: "Faminto's",
                       type: "Brasileira",
                       price: "$$-$$$",
                       rating: "4,2",
                       address: "R. Sant'Anna, 12 - Casa Forte",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: false),
            // MARK: - mood: ELEGANTE
            RestByMood(mood: "elegante",
                       name: "Vetro Ristrot e Fusion Lounge",
                       type: "Italiana, Francesa",
                       price: "$$$$",
                       rating: "4,7",
                       address: "Av. Conselheiro Aguiar, 916 - Boa Viagem",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "elegante",
                       name: "Vasto",
                       type: "Japonesa, Frutos do Mar",
                       price: "$$$$",
                       rating: "4,9",
                       address: "1° Piso Shopping Recife, R. Padre Carapuceiro, 777 - Boa Viagem",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "elegante",
                       name: "Casa do Vinho Al Mare",
                       type: "Wine Bar",
                       price: "$$$$",
                       rating: "4,1",
                       address: "R. Manuel Borba, 338 - Carmo",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "elegante",
                       name: "Bargaço",
                       type: "Brasileira, Frutos do Mar",
                       price: "$$$-$$$$",
                       rating: "4,6",
                       address: "Av. Antônio de Goes, 62, Pina",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        
                       ],
                       drinks: true),
            RestByMood(mood: "elegante",
                       name: "The Black Angus",
                       type: "Brasileira, Steakhouse, Wine Bar",
                       price: "$$$-$$$$",
                       rating: "4,3",
                       address: "R. França Pereira, 146 - Boa Viagem",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "elegante",
                       name: "Tio Armênio",
                       type: "Brasileira, Internacional, Contemporânea",
                       price: "$$-$$$",
                       rating: "4,6",
                       address: "R. Padre Carapuceiro, 777 - 423, Boa Viagem",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "elegante",
                       name: "Papacapim",
                       type: "Italiana, Brasileira",
                       price: "$$",
                       rating: "4,5",
                       address: "Av. Rui Barbosa, 1397 - Graças",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "elegante",
                       name: "La Pecora Nera",
                       type: "Italiana",
                       price: "$$$$",
                       rating: "4,5",
                       address: "Praça de Casa Forte, 505 - Casa Forte",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "elegante",
                       name: "Nikko Japanese Fusion",
                       type: "Japonesa",
                       price: "$$$-$$$$",
                       rating: "4,3",
                       address: "Av. Conselheiro Aguiar, 1712 - Boa Viagem",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        
                       ],
                       drinks: true),
            RestByMood(mood: "elegante",
                       name: "Quina do Futuro",
                       type: "Japonesa",
                       price: "$$$$",
                       rating: "4,6",
                       address: "R. Xavier Marques, 134 - Aflitos",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true),
            RestByMood(mood: "elegante",
                       name: "Sumô Sushi Bar",
                       type: "Japonesa",
                       price: "$$-$$$",
                       rating: "4,5",
                       address: "R. Xavier Marques, 87 - Graças",
                       maskImage: "",
                       backImage: "",
                       filters: [
                        "Vegano",
                        "Vegetariano"
                       ],
                       drinks: true)
            
        ]
    }
}
